### ISSUE TITLE
ご連絡ありがとうございます。

### ISSUE THREAD

**Issue by nagasawajun** [soja-suidou/enkan_suidou#1]
掲示板のご連絡ありがとうございます。
開札結果を聞いていないのですが、落札者アイ・サポートだったのでしょうか。

**Comment by isupport-kitta** [comment]
TEST

**Comment by soja-suidou** [comment]
落札です。
本日中にクラウドの仮作業領域を作成してデータを転送いたします。

**Comment by nagasawajun** [comment]
ありがとうございます。どうぞよろしくお願いいたします。
