### ISSUE TITLE
下記設定について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/enkan_suidou#10]
https://github.com/yamamoto-ryuzo/QGIS-exportExcel
https://github.com/yamamoto-ryuzo/GEO-search-plugin
の二つの設定も可能なようならお願いしようと思います。
サイト見てどんなかんじでしょうか？
特に、エクセル連携は今後の発注に大きく影響します。
一度すればとても簡単です。
これをみて理解出来ればプロジェクトファイル作成者として一人前です。

**Comment by nagasawajun** [comment]
QGISのプロジェクトファイルに、以下の2つの機能を設定するということでしょうか。
・エクスポート機能
・検索機能
（どちらもソースコードはあるので設定のみ）

パッと見ては理解できなかったので少し分析のお時間をください。

**Comment by yamamoto-ryuzo** [comment]
ほとんど所定の位置に置いて、プロジェクト変数を設定するだけです。

**Comment by yamamoto-ryuzo** [comment]
下記のような感じです。
プロジェクトファイルを実際に見てもらって方がいいです。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/c409924a-3a35-44bd-8494-c92a38788974)
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/d6a6cd8d-990f-4d5c-9577-907fbf53e414)
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/4c402a3d-3f2a-4468-95e3-5ccf5e8a948a)
↑にPython張り付ける

**Comment by nagasawajun** [comment]
ありがとうございます。見てみます。

**Comment by nagasawajun** [comment]
お世話になっております。
本件、対応中です。
明日には、結果のご報告もしくは一部質問をさせていただきます。
弊社の山本よりご連絡させていただきます。

**Comment by yamamoto-IS** [comment]
山本様
お世話になっております。アイ・サポートの山本です。
プラグインの設定につきまして、資料を確認いたしました。
QGIS-exportExcelにつきましてはおおむね理解することができました。

Ryuzo/GEO-search-pluginにつきましては、
setting.json.sampleの内容をsetting.jsonに張り付けていったん画面表示ができることは確認しましたが、
データ設定の参照先が分からないため、検索機能の利用設定ができていない状態です。
お手数おかけしますが、具体的な設定の参照先をご教授いただけますと幸いです。

![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/31925b73-0e1a-41b0-9c0a-48426353c648)

**Comment by yamamoto-ryuzo** [comment]
それ！設定が面倒なので今後簡略化の予定です。
まずは下記を確認ください。
当分はこれでOKだと思います。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/9e1556f4-dff9-4c96-a8e0-b0ab216adcdb)
この部分の機能です。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/97c33f28-3501-4d0e-9560-2fb4d2156e0e)
プロジェクト単位に設定できます。
再設定時は再読み込みが必要です。

**Comment by yamamoto-IS** [comment]
@yamamoto-ryuzo 
山本様　
設定の詳細ありがとうございます。
別のレイヤーで下記設定の通り設定することで、
検索機能が利用できること確認できました。

QGIS-exportExcel
GEO-search-plugin
二つのプラグインについて設定方法理解しました。
よろしくお願いします。

![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/406f8e8a-d50f-4d5d-ad98-eec90b90520d)

**Comment by yamamoto-ryuzo** [comment]
本年度発注予定の占用台帳関連のシステム構築において必須となりますので、よろしくお願いいたします。
以上。
