### ISSUE TITLE
変更について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/enkan_suidou#11]
実は，現在，賦課漏れが下水道課であった関係で，上水道課も業務の流れ上，理論的に破綻しているもの見直しを行っております。
　その過程で，今回のデータも，そちらのシステムで統合データとして利用したいので，今回は，ＰＯＳＴＧＩＳへの移行は時期尚早となりました。
　そのため，下記を中止します。

~~（６）中間協議　　　　　　　　　　　　　　　１人
　　　・シンボル及び属性の表示方法の確認
（７）最終調整　　　　　　　　　　　　　　　１人
　　　・中間協議による調整を行うもの
（８）一時納品　　　　　　　　　　　　　　　１人
　　　・ＬＧＷＡＮ（ＰｏｓｔＧＩＳ）への設置~~

　そのうえで，台帳上の弁尖デーがポイントになっているので，それをきれいにしようと思います。
　数日以内には指示予定です。
　今しばらくお待ちください。
　
　なお，最新データは置き換えておいてあります。
　ﾊﾞｯｸｱｯﾌﾟは，バックアップ領域においてます。
　ファイリング機能はLGWANになっているので，クラウドでは動作しません。

　以上。

**Comment by yamamoto-ryuzo** [comment]
（１）業務打合せ　　　　　　　　　　　　　　１人  
　　　・成果品の内容確認  
（２）既存ファイルの確認　　　　　　　　　　１人  
　　　・重複ファイル等の内容確認  
　　　・最終ファイルであるかどうかが不明な場合は，全てのデータを表示し，中間協議時に，最終データの選択を発注者が行うものとする。  
（３）ＧＩＳ関連ファイルの読み込み　　　　　１人  
　　　・ＳＩＳ若しくはＭａｐＩｎｆｏによる読込テストを実施のこと  
　　　・納品用最終ファイルはジオパッケージとし，プロジェクトフォルダと同一フォルダに格納のこと  
（４）エクセル・データベース及び資料の連携　**２．５人（＋１．５人）**  
　　　**・エクセル・データベースファイルとＭａｐＩｎｆｏファイルの整合チェック（変更＋１．５人）**  
　　　・必要に応じてジオパッケージの属性に取り込むこと  
　　　・資料については，地物よりフォルダへのファイリング機能を設定すること  
（５）表示形式の設定　　　　　　　　　　　　**２．５人（＋１．５人）**   
　　　・シンボル及び属性の表示方法の設定  
　　　・シンボルは市が提供するシンボルを利用のこと  
　　　**・シンボルのカスタマイズ（変更＋１．５人）**    

に修正しました。
仕様書変更は最終でお送りします。
今回は，仕様書のとおり，増減なしでお願いします。

**Comment by nagasawajun** [comment]
仕様書変更について承知いたしました。
増減なしとのことで、ありがとうございます。

**Comment by yamamoto-ryuzo** [comment]
明日，議会の委員会が終わったら仕様書も変更して修正しますので，その後納品お願いいたします。

**Comment by nagasawajun** [comment]
ありがとうございます。仕様書変更についても承知いたしました。

**Comment by yamamoto-ryuzo** [comment]
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築
に変更仕様書を置いていますので，併せて納品ください。
以上。

**Comment by nagasawajun** [comment]
報告書・請求書データを以下の場所に保存しました。
\\soja\総社市\市役所⇔アイ・サポート\R05報告書\総社市鉛管・受水槽台帳閲覧システム構築

請求書の日付は空欄で提出させていただこうと思っております。

報告書は印刷製本の上、請求書と併せて山本課長宛に発送させていただこうと思います。

どうぞよろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
仕様書に誤字があったので，その関係を修正（"タ"が抜けてました）しておきました。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/49cfc63c-e521-44c7-a1f6-aeb7a23a320e)

請求書は日付空欄でお願いします。
各作業で行ったチェックシート等も作業内容に合わせて添付ください。

**Comment by nagasawajun** [comment]
ありがとうございます。各作業のチェックシート等も添付するようにいたします。

**Comment by nagasawajun** [comment]
\\soja\総社市\市役所⇔アイ・サポート\R05報告書\総社市鉛管・受水槽台帳閲覧システム構築
の下に4つフォルダを作成しました。
この下に保存しているファイルを添付ファイルとさせていただきます。
9/14には届くようにいたします。
以上ご報告です。
