### ISSUE TITLE
SVGファイルの作成について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/enkan_suidou#12]
現在，水道の弁についてパブリックドメインのSVGファイル作成を検討しております。
色のパラメータを後からQGISで変更できる設定のSVGファイルの作成は可能でしょうか。
可能であればお願いしようと思います。
参考のSVGファイル等は別途お送りします。
下の正式版です。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/9c1e70df-93b5-4bce-a9c9-91353c381ac4)

**Comment by nagasawajun** [comment]
svgについて、調べます。また、明日回答させてください。

**Comment by nagasawajun** [comment]
以下のソフトを使うとSVGファイルが作れるようでした。
https://inkscape.org/ja/about/overview/
他にもおすすめソフトがありましたら教えてください。

作業期間をある程度見ていただけたら対応可能です。
どうぞよろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
ソフトはどれがというのはないですが，実績がないのでしたら，今回は，簡単なところからお願いします。
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\QGIS納品領域\symbol\svg\water
に公開OKでいただいたデータがあるので，その手直しおよびGISへの設定をお願いします。
