### ISSUE TITLE
（５）表示形式の設定　シンボルのカスタマイズ

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/enkan_suidou#13]
他業者からいただいたパブリックドメインの下記データのカスタマイズです。

\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\QGIS納品領域\symbol\svg\water
のデータをQGISで色・線幅・透明度を変更できるようにカスタマイズお願いします。  
具体的には，  
dummy_meter.svg　＞　dummy_meter(変換サンプル).svg  

内容はメモ帳でファイルを開いて  

```<path class="C3" d="M0.5765 -2.2071L0.5767 -2.5543L0.5764 -2.5581L0.5753 -2.5617L0.5736 -2.5651L0.5712 -2.5681L0.5683 -2.5706L0.5650 -2.5725L0.5614 -2.5737L0.5577 -2.5743L0.5539 -2.5741L0.5502 -2.5732L0.5467 -2.5716L0.2457 -2.3976L0.2426 -2.3954L0.2400 -2.3926L0.2379 -2.3894L0.2365 -2.3859L0.2358 -2.3822L0.2358 -2.3784L0.2365 -2.3746L0.2379 -2.3711L0.2400 -2.3679L0.2426 -2.3652L0.2457 -2.3630L0.5465 -2.1898L0.5500 -2.1882L0.5537 -2.1873L0.5575 -2.1871L0.5612 -2.1877L0.5648 -2.1889L0.5681 -2.1908L0.5710 -2.1933L0.5733 -2.1963L0.5751 -2.1997L0.5761 -2.2033L0.5765 -2.2071zM0.5365 -2.2417L0.2957 -2.3803L0.5367 -2.5196L0.5365 -2.2417z"/>  ```

の行を  

```<path class="C3" d="M0.5765 -2.2071L0.5767 -2.5543L0.5764 -2.5581L0.5753 -2.5617L0.5736 -2.5651L0.5712 -2.5681L0.5683 -2.5706L0.5650 -2.5725L0.5614 -2.5737L0.5577 -2.5743L0.5539 -2.5741L0.5502 -2.5732L0.5467 -2.5716L0.2457 -2.3976L0.2426 -2.3954L0.2400 -2.3926L0.2379 -2.3894L0.2365 -2.3859L0.2358 -2.3822L0.2358 -2.3784L0.2365 -2.3746L0.2379 -2.3711L0.2400 -2.3679L0.2426 -2.3652L0.2457 -2.3630L0.5465 -2.1898L0.5500 -2.1882L0.5537 -2.1873L0.5575 -2.1871L0.5612 -2.1877L0.5648 -2.1889L0.5681 -2.1908L0.5710 -2.1933L0.5733 -2.1963L0.5751 -2.1997L0.5761 -2.2033L0.5765 -2.2071zM0.5365 -2.2417L0.2957 -2.3803L0.5367 -2.5196L0.5365 -2.2417z"  fill="param(fill)" fill-opacity="param(fill-opacity)" stroke="param(outline)" stroke-opacity="param(outline-opacity)" stroke-width="param(outline-width)"/>  ```

とするだけです。  

  **fill="param(fill)" fill-opacity="param(fill-opacity)" stroke="param(outline)" stroke-opacity="param(outline-opacity)" stroke-width="param(outline-width)"**  
  を追加するだけです。

**Comment by yamamoto-ryuzo** [comment]
一応すべてのSVGを　色等が変更できているかQGISで確認ください。
そのうえで，シンボルを適宜適用ください。
角度も属性にあると思うので，併せてしてしてください。
線の幅やサイズも見直しが必要です。
現在の設定は一度リセットされます。

**Comment by yamamoto-ryuzo** [comment]
追伸
SVGシンボルにするとワンサイズ小さく見えるので，その辺のサイズ調整もお願いします。
以上。

**Comment by nagasawajun** [comment]
簡単なところからのご配慮、誠にありがとうございます。
追って対応させていただきます。

**Comment by yamamoto-IS** [comment]
@yamamoto-ryuzo 山本様
>\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\QGIS納品領域\symbol\svg\water
>のデータをQGISで色・線幅・透明度を変更できるようにカスタマイズお願いします。
⇒対象のファルダ内のSVGファイルをQGIS上で変更できるように修正いたしましたので、
　ご確認よろしくお願いいたします。
　
総社市鉛管・受水槽台帳閲覧システム.qgs上の消火栓と仕切弁については、SVGファイルを添付してシンボル情報を更新しております。その他のSVGファイルについては、ファイルのみを更新しております。

**Comment by yamamoto-ryuzo** [comment]
１．回転の属性があったと思います。
設定をお願いします。

２．表示順を変えたらバルブの白が役に立つはずです。

３．仮にGISで表示して確認の上報告ください。

以上。

**Comment by yamamoto-IS** [comment]
１．につきまして、
回転属性の設定はこの設定を行うという認識でよろしいでしょうか？
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/cf8aed2e-0d07-4882-9be9-d516d5523cef)

３．
表示上はこのようになります。
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/fe358986-dd38-401c-8dcf-c01b5468baad)

**Comment by yamamoto-ryuzo** [comment]
１．回転の属性があったと思います。
　属性を　式　で回転させれば＋９０°どかで回転すればいい感じにならないです？
　また，サイズもほかと合わせて　式　でスケール調整してください。

２．表示順を変えたらバルブの白が役に立つはずです。
　レイヤの表示順を変えたら綺麗にならないですか？
　ちなみに，記号とラベルの関係は確認の上設定ください。

　不明なものは一度社内で **「連携を構築」** してみてください。
　いろいろできる人が単独で勉強しても **「全体としての連携ができていないと受注者として長続きしない」** ので。

　そのうえで，不明な点は再度ご連絡ください。

　以上。

**Comment by nagasawajun** [comment]
お世話になっております。
社内連携について、ご指摘を申し訳ございません。
連携構築について、再度検討いたします。

実力不足で申し訳ないのですが、質問させてください。
ご依頼は管路に沿わせて、弁栓類を回転させるということでよろしいでしょうか。
現在、調査をしたのですが、弁栓類が管路の角度を取ってくる方法が分かっておりません。
（上記弊社山本の設定で出来たと思ってしまったのですが管路に沿っていないところもありました。）
継続して調査しますが、
もし、山本課長がご存じのことがありましたら教えていただきたく思います。


弁栓類の白が役に立つ件については、レイヤーの表示順を変えることと解釈いたしまして、配水管を弁栓類の背面に表示するように変更しました。

**Comment by yamamoto-ryuzo** [comment]
>現在、調査をしたのですが、弁栓類が管路の角度を取ってくる方法が分かっておりません。

　？ポイントの角度を式で補正ではだめでした？
　式は線の幅で行ってもらったように、ふつうに計算式入れるだけです。
　明日私も確認してみます。
　
※↓の編集で式を選んで、式を記入してください。　
　QGISこの辺りはどれも金太郎あめのようなやり方でOKです。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/5756462f-b529-4ccc-ad7e-84edbbb5af0c)

**Comment by yamamoto-ryuzo** [comment]
大きさも、前回やっていただいたように、式を入力ください。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/a9b71fa1-af36-458a-9a99-a5dff55ec14e)

**Comment by yamamoto-ryuzo** [comment]
線の色・幅等はSVGマーカーを選択して、諸設定をお願いします。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/9a8d4af7-dec9-4741-911b-769e8648097b)

**Comment by nagasawajun** [comment]
ご助言ありがとうございます。
ご助言内容を踏まえまして、再度確認させていただきます。
また、来週くらいになってしまうかもしれないのですが、結果をご報告いたします。

**Comment by yamamoto-ryuzo** [comment]
一覧と確認しましたが，仕切弁の「角度」意味不明でした・・・
これは無理です。
「弁＋○囲み」で今回は対応お願いします。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/88e94e21-cef2-4e15-8a5f-f11d8d058180)

**Comment by yamamoto-ryuzo** [comment]
他の角度も確認しましたが，これ書類作成か何かで生成した角度かもしれません・・・
そんなに重要でないので，消火栓は角度補正なしでおねがいします。
とりあえず「消＋○」で対応お願いします。
その他の弁尖も多少小ぎれいにお願いします。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/bf307fb2-b8bf-4454-a984-6ad3b536dfee)

**Comment by yamamoto-ryuzo** [comment]
追伸
SVGマーカーの設定は「SVGマーカー」を選択して設定してください。
ストローク色とストローク幅の設定が本来は必要です。
このあたりの設定修正もできているか，納品前に確認お願いします。
せっかく設定できるように修正した下記の意味がなくなります。
**fill="param(fill)" fill-opacity="param(fill-opacity)" stroke="param(outline)" stroke-opacity="param(outline-opacity)" stroke-width="param(outline-width)"**
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/b2922325-3a53-475f-b173-a4e8353ed8c8)

**Comment by nagasawajun** [comment]
ご確認ありがとうございました。
仕切弁と消火栓について、文字だけだと間違った認識をしそうなので下図で確認させてください。
表示方法は以下のどちらをお考えでしょうか。

![image](https://github.com/soja-suidou/enkan_suisou/assets/110758944/ef6076a7-2659-4cf1-be14-7e6f7dae0f73)

また、その他弁栓について、管末のような感じなのですが、回転もできないので、以下のように単なる■でよろしいでしょうか。

![image](https://github.com/soja-suidou/enkan_suisou/assets/110758944/17576bc4-f1ce-46ad-9711-fff9a4b96186)

**Comment by yamamoto-ryuzo** [comment]
「消＋○」= ２案のことです。
仕切弁（案）２，消火栓（案）２，■でお願いします。
以上。

**Comment by nagasawajun** [comment]
早速返信をありがとうございます。また、設定が出来ましたらご連絡いたします。

**Comment by yamamoto-IS** [comment]
@yamamoto-ryuzo 　山本様
対応が遅れてしまい申し訳ありません。
仕切弁、消火栓シンボルにつきまして、
SVGファイルを新規で作成し、
シンボルのサイズ・ストロークの設定を行いましたので、
お手数おかけしますが、ご確認よろしくお願いいたします。

![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/5841c64a-affa-49c6-9dd2-4dbd83e3ce53)
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/6fc1c96f-7ff3-4a89-999b-e4d56f5bfeca)

**Comment by yamamoto-IS** [comment]
消火栓、仕切弁、その他弁栓類のSVGを新規に作成しておりますが、
表示上、山本様のイメージと異なる点がありましたら、ご指摘いただけると幸いです。
またSVG作成時の編集エディタの関係で、山本様がご提示いただいているSVGファイルの構造と
こちらで作成したSVGファイルの構造が異なりますが、表示上問題がなければ大丈夫かと思っております。
必要に応じて適宜修正したいと思っておりますので、どうぞよろしくお願い致します。

**Comment by yamamoto-ryuzo** [comment]
スケール設定の見直しについて
　主張が激しいようです。
　弁は弁は付属品のようなものなので，他のスケール設定と合わせた式でOKです。
　今のように細かく分けなくてもいいです。
　スケール及びサイズは適宜調整ください。
　if(@map_scale>=2500,(1/@map_scale*(3.0*2500)),3.0)

![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/7f826d94-75c6-4c73-8f13-2c891c660313)

**Comment by yamamoto-ryuzo** [comment]
>SVGファイルの構造
SVGエディタによって変わるので機能さえ満足すればそれでよいです。

ファイルの保存は，前例に習って命名ください。
同一の場合は_２とか_kanjiとかでもOKです。

ファイルは完成したもののみ
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\QGIS納品領域\symbol\svg\water
に集約ください。

**Comment by yamamoto-ryuzo** [comment]
給水装置のSVG　meter_50.svg　を利用して　-90°　にしてください。
サイズは　if(@map_scale>=2500,(1/@map_scale*(4.0*2500)),4.0)　でお願いします。
線の幅等は適宜設定してください。
色は現在の色を選択ください。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/72659579-68bb-453a-a2d2-a3c235908e01)

色は他のものも同じ色使いをしています。

なので，排水施設はすべて　排水管の青を利用してください。
また，グループ　配水管は中身がないので不要です。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/1dddd24c-8363-4508-8c2f-cacb151c0874)

**Comment by yamamoto-IS** [comment]
@yamamoto-ryuzo 山本様
詳細なご指示いただきありがとうございます。
弁栓類、消火栓シンボルのスケールを調整しました。

作成したSVGファイルについては、下記のフォルダに格納しております。
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\QGIS納品領域\symbol\svg\water
・haisui_sikiriben_kanji.svg
・syoukasen_kanji.svg
・haisui_sonotabensen.svg

給水装置のシンボルについては、スケール、角度調整し、下記の通り設定しました。
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/ab0f1ed7-af28-40e5-9cc0-5066face3998)
配水施設については、下記の通り配水管の青色をそれぞれの施設に配色しました。
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/634cc85d-e063-4370-9615-bfee555be029)
QGIS上のシンボル表示
![image](https://github.com/soja-suidou/enkan_suisou/assets/141702312/3e08821b-bc6e-4c10-a5e3-2e724055cd0a)

お手数おかけしますが、ご確認よろしくお願い致します。

**Comment by yamamoto-ryuzo** [comment]
凡例が小さめなのでもうちょっと大きめがいいです。
今回の場合は2.0　＞＞＞　4.0mm　で大きくなると思います。
![image](https://github.com/soja-suidou/enkan_suisou/assets/86514652/dc5f83a6-fdfe-4135-af51-72d590cd8ff8)

**Comment by yamamoto-ryuzo** [comment]
後は，報告書と合わせて納品ください。
以上。

**Comment by yamamoto-IS** [comment]
山本様
ご確認、ご指摘ありがとうございます。
下記の通り凡例のサイズ調整を行いました。
![MicrosoftTeams-image (1)](https://github.com/soja-suidou/enkan_suisou/assets/141702312/cbb0052e-1005-4d84-9afb-45b41509bca0)
サイズは3.6mmがきれいに表示されたので3.6mmで設定しております。
