### ISSUE TITLE
クラウド領域の削除について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/enkan_suidou#14]
@nagasawajun 
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築
　業務終了に伴い，上記フォルダを削除てよいですがよろしいでしょうか。
　以上。

**Comment by nagasawajun** [comment]
はい、削除お願いいたします。
今後は、業務が終わったら、弊社から総社市の担当者様にご連絡して、フォルダを消すようにした方が良いでしょうか。

**Comment by yamamoto-ryuzo** [comment]
先ほど削除いたしました。
どれが最終かわからなくなるので，業務終了後クラウドにない方がいいものは，削除がいいと思います。
今回の業務のような場合は，クラウドはあくまで業務の作業をスムースにするところとして利用しただけなので。
どちらが削除するかはその都度協議お願いします。
一度消したらそれで終わりなので。

ただ，念のため，今後の納品時には，必ずDVD（２枚・正・副）で最終データの納品を行うようにお願いします。
