### ISSUE TITLE
作業内容の確認

### ISSUE THREAD

**Issue by nagasawajun** [soja-suidou/enkan_suidou#3]
データ設定ありがとうございます。
以下の作業内容であっていますでしょうか。

（３）ＧＩＳ関連ファイルの読み込み　　　　　１人
　　　・ＳＩＳ若しくはＭａｐＩｎｆｏによる読込テストを実施のこと
→読み込むのは以下のファイル
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\DATA\受水槽
T受水槽調査結果.TAB

\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\DATA\tab
鉛管資料調査.TAB

\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\MAP\鉛管
M鉛管現地調査.TAB

\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\MAP\受水槽
受水槽位置.TAB

・納品用最終ファイルはジオパッケージとし，プロジェクトフォルダと同一フォルダに格納のこと

（４）エクセル・データベース及び資料の連携　１人
　　　・必要に応じてジオパッケージの属性に取り込むこと
→以下のファイルを見て紐づけできそうだったら行う。
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\DATA
T受水槽調査結果.accdb
鉛管受水槽.mdb

　　　・資料については，地物よりフォルダへのファイリング機能を設定すること
→ファイリング設定するのは、以下のフォルダ
\\soja\総社市\総社市鉛管・受水槽台帳閲覧システム構築\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\平成１５年度　総社市鉛管・受水槽実態調査業務委託（２０２３－０７－１４受領+総社市データ）\受水槽資料

（５）表示形式の設定　　　　　　　　　　　　１人
　　　・シンボル及び属性の表示方法の設定
　　　・シンボルは市が提供するシンボルを利用のこと
→シンボルのご提供お願いします。

**Comment by yamamoto-ryuzo** [comment]
まずは
https://github.com/soja-suidou/enkan_suisou/issues/4
をお願いします。
その結果，上位になれば正解です。

**Comment by yamamoto-ryuzo** [comment]
シンボルに関しては
https://github.com/soja-suidou/enkan_suisou/issues/5
でお願いします。
